flowchart TD
    A[Client App] -- SSR --> B(Firebase Hosting)
    B -- API Calls --> C(Firebase Functions)
    C -- Authentication --> D(Firestore Auth)
    D -- Valid Token --> E((Backend Services on Fly.io))
    E -- Firestore Access --> F(Firestore easyscrape DB)
    E -- Stripe API --> G(Stripe)
    E -- Redis Queue --> H(Upstash Redis)
    H -- Queue Operations --> I((Backend Processing))
    I -- Queue Operations --> I4(Custom Crawler Queue App)

    E -- Image Deployment API--> I1(dedicated api service app)
    E -- Crawler4AI Standard Deployment API --> I2(crawler4ai standard api service)
    E -- Custom Crawler4AI Deployment API --> I3(custom crawler api service)
    E -- Shared Fixed Crawler4AI Deployment API--> I5(shared fixed platform's api service app)
    
    %% Updated part to indicate Express server for Client App
    subgraph SSR_Express_Server
        direction TB
        A
    end

    subgraph LoadBalancer
        LB[Load Balancer]
    end
    LB --> E

    E -- Cache --> CacheLayer[Redis Cache]
    CacheLayer -- Firestore Access --> F

    subgraph Monitoring
        M[Monitoring & Logging Service]
    end
    E --> M

    CDN[Content Delivery Network] --> B

    F -- Backup --> BackupService[Backup Storage]
    H -- Backup --> BackupService


style A fill:#90EE90,stroke:#333,stroke-width:2px,color:black
style B fill:#87CEFA,stroke:#333,stroke-width:2px,color:black
style C fill:#FFFFE0,stroke:#333,stroke-width:2px,color:black
style D fill:#FFA07A,stroke:#333,stroke-width:2px,color:black
style E fill:#87CEFA,stroke:#333,stroke-width:2px,color:black
style F fill:#8FBC8F,stroke:#333,stroke-width:2px,color:black
style G fill:#EEE8AA,stroke:#333,stroke-width:2px,color:black
style H fill:#D3D3D3,stroke:#333,stroke-width:2px,color:black
style I fill:#A53B3BFF,stroke:#333,stroke-width:2px,color:white
style I1 fill:#87CEFA,stroke:#333,stroke-width:2px,color:black
style I2 fill:#87CEFA,stroke:#333,stroke-width:2px,color:black
style I3 fill:#87CEFA,stroke:#333,stroke-width:2px,color:black
style I4 fill:#042E47FF,stroke:#333,stroke-width:2px,color:white
style I5 fill:#87CEFA,stroke:#333,stroke-width:2px,color:black