import {

    Home,
    FileText,
    Zap,
    Monitor,
    Search,
    Globe,
    Brain,
    Network,
    Database,
    Code,
    Shield,
    Gauge,
    Bot,
    Menu,
    LucideIcons,
    ShieldCheck,
    Settings,
    UserRound,
    Fingerprint,
    PiggyBank,
    LucidePiggyBank,
    KeyRound,
    CircleCheckBig,
    GithubIcon,
    Twitter,
    Linkedin,
    Mail,
} from 'lucide-angular'

export let myIcons: LucideIcons = {
    home: Home,
    menu: Menu,
    bot: Bot,
    gauge: Gauge,
    shield: Shield,
    database: Database,
    code: Code,
    network: Network,
    brain: Brain,
    globe: Globe,
    filetext: FileText,
    search: Search,
    monitor: Monitor,
    zap: Zap,
    shieldcheck: ShieldCheck,
    settings: Settings,
    "user-round": UserRound,
    fingerprint: Fingerprint,
    "piggy-bank": LucidePiggyBank,
    "key-round": KeyRound,
    'circle-check-big': CircleCheckBig,
    github: GithubIcon,
    x: Twitter,
    linkedin: Linkedin,
    mail: Mail,

}