import {

    Home,
    FileText,
    Zap,
    Monitor,
    Search,
    Globe,
    Brain,
    Network,
    Database,
    Code,
    Shield,
    Gauge,
    Bot,
    Menu,
    LucideIcons,
    ShieldCheck,
    Settings,
    UserRound,
    Sparkles,
    Fingerprint,
    PiggyBank,
    LucidePiggyBank,
    KeyRound,
    CircleCheckBig,
    FingerprintIcon,
    GithubIcon,
    Twitter,
    Linkedin,
    Mail,
    RefreshCcw,
    BarChart,
    PieChart,
    Activity,
    Users,
    ListOrdered,
    LineChart,
    LayoutGrid,
    UserPlus,
    Repeat,
    ArrowRight,
    ShoppingBag,
    Target,
    ChevronDown,
    Send,
    MessageCircle,
    PenLine,
    CheckCircle,
    Check,
    Play,
    Server,
    Cpu,
    Rocket,
    Layers,
    Loader,
    LoaderCircle,
    Boxes,
    GitBranch,
    Terminal,
    RefreshCw,
    MousePointerClick,
} from 'lucide-angular'

export let myIcons: LucideIcons = {
    home: Home,
    menu: Menu,
    bot: Bot,
    gauge: Gauge,
    shield: Shield,
    database: Database,
    code: Code,
    network: Network,
    brain: Brain,
    globe: Globe,
    filetext: FileText,
    search: Search,
    monitor: Monitor,
    zap: Zap,
    shieldcheck: ShieldCheck,
    settings: Settings,
    "user-round": UserRound,
    fingerprint: Fingerprint,
    "piggy-bank": LucidePiggyBank,
    "key-round": KeyRound,
    'circle-check-big': CircleCheckBig,
    github: GithubIcon,
    x: Twitter,
    linkedin: Linkedin,
    mail: Mail,
    'refresh-ccw': RefreshCcw,
    'arrowright': ArrowRight,
    'sparkles': Sparkles,
    'guest-conversion': PieChart,
    'guest-activity': Activity,
    'browser-distribution': Globe,
    'device-types': Monitor,
    'top-countries': ListOrdered,
    'operating-systems': LayoutGrid,
    'recent-activity': LineChart,
    'daily-activity': BarChart,
    'peak-hours': Activity,
    'login-methods': Users,
    'user-distribution': Users,
    'user-plus': UserPlus,
    'repeat': Repeat,
    'shoppingbag': ShoppingBag,
    'target': Target,
    'chevronDown': ChevronDown,
    'send': Send,
    'message-circle': MessageCircle,
    'pen-line': PenLine,
    'check-circle': CheckCircle,
    'check': Check,
    'play': Play,
    'server': Server,
    'cpu': Cpu,
    'rocket': Rocket,
    'layers': Layers,
    'loader': Loader,
    'loader-circle': LoaderCircle,
    'boxes': Boxes,
    'git-branch': GitBranch,
    'terminal': Terminal,
    'refresh-cw': RefreshCw,
    'mouse-pointer-click': MousePointerClick,
}